### PR TITLE
Add types

### LINKED ISSUE #10: Add types
``` js
var types = require('pg').types
types.setTypeParser(20, function(val) {
  return parseInt(val)
})
```

Documentation here: https://www.npmjs.com/package/pg-types

### PR DESCRIPTION
**Pull request by felixfbecker**
See https://github.com/brianc/node-pg-types
Closes #10

### CODE REVIEW

**Comment by goenning** [comment]
Thanks for the contrib. I'll wait to merge it with `vnext` branch, I hope that it won't take long.

**Comment by felixfbecker** [comment]
@goenning would it be a major effort to merge this now into the current version? Or maybe we could open a new typings repo for `pg-types` (since it's actually a seperate module)? We would like to depend on this asap

**Comment by goenning** [comment]
I can't image someone using pg-types alone, so I think we are OK with that for now.

**Comment by felixfbecker** [comment]
Thanks for merging!

**Pull request merged**
